### ISSUE TITLE
Replace CMS logo with correct one

### ISSUE THREAD

**Issue by RaoOfPhysics** [mattbellis/Particle-Physics-Playground#1]
Looks like the CMS logo was taken from the CMS website when it was in beta stage (hence the beta symbol on it). Perhaps you can replace it with an appropriate one from here:

https://cms-docdb.cern.ch/cgi-bin/PublicDocDB/ShowDocument?docid=3045&version=3

**Comment by mattbellis** [comment]
Fixed! Thanks! This was effectively a scratch version of the site that my student worked on last summer. A new version should be available soon, but at least we'll have the proper logo in the meantime.  :)

**Comment by RaoOfPhysics** [comment]
@mattbellis: Thanks for the fix! Feel free to ping me if you need anything from a CMS outreach perspective. I'd like to help and use GitHub a lot more to contribute to projects.

**Comment by mattbellis** [comment]
I will ping you. I'm planning on moving the site to a better organized version that one of the Siena CS profs is helping me put together. When it's up, I'll let you know to get another opinion...or help with the organization.  :)   Will be in touch soon!
